version: "3.5"

networks:
  container-link:
    driver: bridge

services:
  db:
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
    env_file: ./docker/.env.local
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - 5432:5432
    networks:
      - container-link